title: NightPhoenixGH's Website
author: NightPhoenixGH
email: nightphoenix.gh@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  NightPhoenixGH's projects website
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

url: "https://nightphoenixgh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /posts/:title/
github_username:  nightphoenixgh
texture:
  title: Federico d'Alonzo
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  nightphoenixgh
    #linkedIn: in/thelehhman
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - texture.gemspec
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
